/**
 * @module TrustLevel
 */

'use strict'

module.exports = {
  KNOWN_TRUSTED_INSTALLER: 100,
  KNOWN_TRUSTED: 99,
  MOST_LIKELY_TRUSTED: 85,
  MIGHT_BE_TRUSTED: 70,
  UNKNOWN: 50,
  MIGHT_BE_MALICIOUS: 30,
  MOST_LIKELY_MALICIOUS: 15,
  KNOWN_MALICIOUS: 1,
  NOT_SET: 0
}
